context("space")

testSpace = function(name, in.dim, out.dim, lower, upper, ...) {
  test_that(name, {
    f = generateMOO(name, in.dim, out.dim, ...)
    par.set = getParamSet(f)
    expect_equal(as.numeric(getLower(par.set)), lower)
    expect_equal(as.numeric(getUpper(par.set)), upper)
  })
}

testSpace("zdt1", in.dim = 2L, out.dim = 2L, lower = rep(0, 2), upper = rep(1, 2))
testSpace("zdt2", in.dim = 2L, out.dim = 2L, lower = rep(0, 2), upper = rep(1, 2))
testSpace("zdt3", in.dim = 2L, out.dim = 2L, lower = rep(0, 2), upper = rep(1, 2))
testSpace("zdt4", in.dim = 2L, out.dim = 2L, lower = c(0, -5), upper = c(1, 5))
testSpace("zdt5", in.dim = 2L, out.dim = 2L, lower = rep(0, 2), upper = rep(1, 2))
testSpace("zdt6", in.dim = 2L, out.dim = 2L, lower = rep(0, 2), upper = rep(1, 2))

testSpace("dtlz1", in.dim = 2L, out.dim = 2L, lower = rep(0, 2), upper = rep(1, 2))
testSpace("dtlz2", in.dim = 2L, out.dim = 2L, lower = rep(0, 2), upper = rep(1, 2))
testSpace("dtlz3", in.dim = 2L, out.dim = 2L, lower = rep(0, 2), upper = rep(1, 2))
testSpace("dtlz4", in.dim = 2L, out.dim = 2L, lower = rep(0, 2), upper = rep(1, 2))
testSpace("dtlz5", in.dim = 2L, out.dim = 2L, lower = rep(0, 2), upper = rep(1, 2))
testSpace("dtlz6", in.dim = 2L, out.dim = 2L, lower = rep(0, 2), upper = rep(1, 2))
#testSpace("dtlz7", in.dim = 2L, out.dim = 2L, lower = rep(0, 2), upper = rep(1, 2))

testSpace("lz1", in.dim = 3L, out.dim = 2L, lower = rep(0, 3), upper = rep(1, 3))
testSpace("lz2", in.dim = 3L, out.dim = 2L, lower = c(0, -1, -1), upper = rep(1, 3))
testSpace("lz3", in.dim = 3L, out.dim = 2L, lower = c(0, -1, -1), upper = rep(1, 3))
testSpace("lz4", in.dim = 3L, out.dim = 2L, lower = c(0, -1, -1), upper = rep(1, 3))
testSpace("lz5", in.dim = 3L, out.dim = 2L, lower = c(0, -1, -1), upper = rep(1, 3))
testSpace("lz6", in.dim = 5L, out.dim = 3L, lower = c(0, 0, rep(-2, 3)), upper = c(1, 1, rep(2, 3)))
testSpace("lz7", in.dim = 3L, out.dim = 2L, lower = rep(0, 3), upper = rep(1, 3)) 
testSpace("lz8", in.dim = 3L, out.dim = 2L, lower = rep(0, 3), upper = rep(1, 3))
testSpace("lz9", in.dim = 3L, out.dim = 2L, lower = c(0, -1, -1), upper = rep(1, 3))

testSpace("uf1", in.dim = 3L, out.dim = 2L, lower = c(0, -1, -1), upper = rep(1, 3))
testSpace("uf2", in.dim = 3L, out.dim = 2L, lower = c(0, -1, -1), upper = rep(1, 3))
testSpace("uf3", in.dim = 3L, out.dim = 2L, lower = rep(0, 3), upper = rep(1, 3))
testSpace("uf4", in.dim = 3L, out.dim = 2L, lower = c(0, -2, -2), upper = c(1, 2, 2))
testSpace("uf5", in.dim = 3L, out.dim = 2L, lower = c(0, -1, -1), upper = rep(1, 3))
testSpace("uf6", in.dim = 3L, out.dim = 2L, lower = c(0, -1, -1), upper = rep(1, 3))
testSpace("uf7", in.dim = 3L, out.dim = 2L, lower = c(0, -1, -1), upper = rep(1, 3))
testSpace("uf8", in.dim = 5L, out.dim = 3L, lower = c(0, 0, rep(-2, 3)), upper = c(1, 1, rep(2, 3)))
testSpace("uf9", in.dim = 5L, out.dim = 3L, lower = c(0, 0, rep(-2, 3)), upper = c(1, 1, rep(2, 3)))
testSpace("uf10", in.dim = 5L, out.dim = 3L, lower = c(0, 0, rep(-2, 3)), upper = c(1, 1, rep(2, 3)))

testSpace("cf1", in.dim = 3L, out.dim = 2L, lower = rep(0, 3), upper = rep(1, 3))
testSpace("cf2", in.dim = 3L, out.dim = 2L, lower = c(0, -1, -1), upper = rep(1, 3))
testSpace("cf3", in.dim = 3L, out.dim = 2L, lower = c(0, -2, -2), upper = c(1, 2, 2))
testSpace("cf4", in.dim = 3L, out.dim = 2L, lower = c(0, -2, -2), upper = c(1, 2, 2))
testSpace("cf5", in.dim = 3L, out.dim = 2L, lower = c(0, -2, -2), upper = c(1, 2, 2))
testSpace("cf6", in.dim = 4L, out.dim = 2L, lower = c(0, -2, -2, -2), upper = c(1, 2, 2, 2))
testSpace("cf7", in.dim = 4L, out.dim = 2L, lower = c(0, -2, -2, -2), upper = c(1, 2, 2, 2))
testSpace("cf8", in.dim = 5L, out.dim = 3L, lower = c(0, 0, rep(-4, 3)), upper = c(1, 1, rep(4, 3)))
testSpace("cf9", in.dim = 5L, out.dim = 3L, lower = c(0, 0, rep(-2, 3)), upper = c(1, 1, rep(2, 3)))
testSpace("cf10", in.dim = 5L, out.dim = 3L, lower = c(0, 0, rep(-2, 3)), upper = c(1, 1, rep(2, 3)))

testSpace("wfg1", in.dim = 5L, out.dim = 2L, k = 3L, lower = rep(0, 5), upper = 2 * 1:5)
testSpace("wfg2", in.dim = 5L, out.dim = 2L, k = 3L, lower = rep(0, 5), upper = 2 * 1:5)
testSpace("wfg3", in.dim = 5L, out.dim = 2L, k = 3L, lower = rep(0, 5), upper = 2 * 1:5)
testSpace("wfg4", in.dim = 5L, out.dim = 2L, k = 3L, lower = rep(0, 5), upper = 2 * 1:5)
testSpace("wfg5", in.dim = 5L, out.dim = 2L, k = 3L, lower = rep(0, 5), upper = 2 * 1:5)
testSpace("wfg6", in.dim = 5L, out.dim = 2L, k = 3L, lower = rep(0, 5), upper = 2 * 1:5)
testSpace("wfg7", in.dim = 5L, out.dim = 2L, k = 3L, lower = rep(0, 5), upper = 2 * 1:5)
testSpace("wfg8", in.dim = 5L, out.dim = 2L, k = 3L, lower = rep(0, 5), upper = 2 * 1:5)
testSpace("wfg9", in.dim = 5L, out.dim = 2L, k = 3L, lower = rep(0, 5), upper = 2 * 1:5)

testSpace("mop1", in.dim = 1L, out.dim = 2L, lower = -10e5, upper = 10e5)
testSpace("mop2", in.dim = 2L, out.dim = 2L, lower = rep(-4, 2), upper = rep(4, 2))
testSpace("mop3", in.dim = 2L, out.dim = 2L, lower = rep(- pi, 2), upper = rep(pi, 2))
testSpace("mop4", in.dim = 3L, out.dim = 2L, lower = rep(-5, 3), upper = rep(5, 3))
testSpace("mop5", in.dim = 2L, out.dim = 3L, lower = rep(-30, 2), upper = rep(30, 2))
testSpace("mop6", in.dim = 2L, out.dim = 2L, lower = rep(0, 2), upper = rep(1, 2))
testSpace("mop7", in.dim = 2L, out.dim = 3L, lower = rep(-400, 2), upper = rep(400, 2))
testSpace("mop_c1", in.dim = 2L, out.dim = 2L, lower = c(0, 0), upper = c(5, 3))
testSpace("mop_c2", in.dim = 6L, out.dim = 2L, lower = c(0, 0, 1, 0, 1, 0), upper = c(10, 10, 5, 6, 5, 10))
testSpace("mop_c3", in.dim = 2L, out.dim = 3L, lower = c(-4, -4), upper = c(4, 4))

testSpace("bk1", in.dim = 2L, out.dim = 2L, lower = rep(-5, 2), upper = rep(10, 2))
testSpace("dgo1", in.dim = 1L, out.dim = 2L, lower = -10, upper = 13)
testSpace("dgo2", in.dim = 1L, out.dim = 2L, lower = -9, upper = 9)
testSpace("fa1", in.dim = 3L, out.dim = 3L, lower = rep(0, 3), upper = rep(1, 3)) 
testSpace("far1", in.dim = 2L, out.dim = 2L, lower = rep(-1, 2), upper = rep(1, 2))
testSpace("fes1", in.dim = 2L, out.dim = 2L, lower = rep(0, 2), upper = rep(1, 2))
testSpace("fes2", in.dim = 2L, out.dim = 3L, lower = rep(0, 2), upper = rep(1, 2))
testSpace("fes3", in.dim = 2L, out.dim = 4L, lower = rep(0, 2), upper = rep(1, 2))
testSpace("ff1", in.dim = 2L, out.dim = 2L, lower = rep(-4, 2), upper = rep(4, 2))
testSpace("ikk1", in.dim = 2L, out.dim = 3L, lower = rep(-50, 2), upper = rep(50, 2))
testSpace("im1", in.dim = 2L, out.dim = 2L, lower = rep(1, 2), upper = c(4, 2))
testSpace("jos1", in.dim = 2L, out.dim = 2L, lower = rep(0, 2), upper = rep(1, 2))
testSpace("jos2", in.dim = 2L, out.dim = 2L, lower = rep(0, 2), upper = rep(1, 2))
testSpace("kur1", in.dim = 2L, out.dim = 2L, lower = rep(0, 2), upper = rep(1, 2))
testSpace("lrs1", in.dim = 2L, out.dim = 2L, lower = rep(-50, 2), upper = rep(50, 2))
testSpace("ltdz1", in.dim = 3L, out.dim = 3L, lower = rep(0, 3), upper = rep(1, 3))
testSpace("le1", in.dim = 2L, out.dim = 2L, lower = rep(-5, 2), upper = rep(10, 2))
testSpace("mhhm1", in.dim = 1L, out.dim = 3L, lower = 0, upper = 1)
testSpace("mhhm2", in.dim = 2L, out.dim = 3L, lower = rep(0, 2), upper = rep(1, 2))
testSpace("mlf1", in.dim = 1L, out.dim = 2L, lower = 0, upper = 20)
testSpace("mlf2", in.dim = 2L, out.dim = 2L, lower = rep(-4, 2), upper = rep(4, 2))
testSpace("qv1", in.dim = 2L, out.dim = 2L, lower = rep(-5.12, 2), upper = rep(5.12, 2))
testSpace("sch1", in.dim = 1L, out.dim = 2L, lower = -6, upper = 6)
testSpace("sp1", in.dim = 2L, out.dim = 2L, lower = rep(0, 2), upper = rep(1, 2))
testSpace("ssfyy1", in.dim = 2L, out.dim = 2L, lower = rep(-100, 2), upper = rep(100, 2))
testSpace("ssfyy2", in.dim = 1L, out.dim = 2L, lower = -100, upper = 100)
testSpace("sk1", in.dim = 1L, out.dim = 2L, lower = 0, upper = 1)
testSpace("sk2", in.dim = 4L, out.dim = 2L, lower = rep(0, 4), upper = rep(1, 4))
testSpace("tkly1", in.dim = 4L, out.dim = 2L, lower = c(0.1, rep(0, 3)), upper = rep(1, 4))
testSpace("vu1", in.dim = 2L, out.dim = 2L, lower = rep(-3, 2), upper = rep(3, 2))
testSpace("vu2", in.dim = 2L, out.dim = 2L, lower = rep(-3, 2), upper = rep(3, 2))
testSpace("vfm1", in.dim = 2L, out.dim = 3L, lower = rep(-2, 2), upper = rep(2, 2))
testSpace("zlt1", in.dim = 2L, out.dim = 2L, lower = rep(-1000, 2), upper = rep(1000, 2))
