#' Generate MOO functions
#' 
#' @param name [\code{character(1)}] \cr
#'   Which MOO function? (DTLZ, ZDT, LZ, UF, CF, WFG, MOP) Small letters and number.
#' @param ...  [\code{any}] \cr
#'   Noch was schreiben
#' @return A \code{mooFunction}.
#' 
#' @aliases MOO moo
#' 
#' @export
#' 
generateMOO = function(name = "", ...) {
  assertCharacter(name)
  
  switch(name,
    zdt1 = generateZDT(id = 1, ...),
    zdt2 = generateZDT(id = 2, ...),
    zdt3 = generateZDT(id = 3, ...),
    zdt4 = generateZDT(id = 4, ...),
    zdt5 = generateZDT(id = 5, ...),
    zdt6 = generateZDT(id = 6, ...),
    dtlz1 = generateDTLZ(id = 1, ...), 
    dtlz2 = generateDTLZ(id = 2, ...), 
    dtlz3 = generateDTLZ(id = 3, ...), 
    dtlz4 = generateDTLZ(id = 4, ...), 
    dtlz5 = generateDTLZ(id = 5, ...), 
    dtlz6 = generateDTLZ(id = 6, ...),
    dtlz7 = generateDTLZ(id = 7, ...),
    lz1 = generateLZ(id = 1, ...),  
    lz2 = generateLZ(id = 2, ...), 
    lz3 = generateLZ(id = 3, ...), 
    lz4 = generateLZ(id = 4, ...), 
    lz5 = generateLZ(id = 5, ...), 
    lz6 = generateLZ(id = 6, ...), 
    lz7 = generateLZ(id = 7, ...), 
    lz8 = generateLZ(id = 8, ...), 
    lz9 = generateLZ(id = 9, ...), 
    uf1 = generateUF(id = 1, ...), 
    uf2 = generateUF(id = 2, ...), 
    uf3 = generateUF(id = 3, ...), 
    uf4 = generateUF(id = 4, ...), 
    uf5 = generateUF(id = 5, ...), 
    uf6 = generateUF(id = 6, ...), 
    uf7 = generateUF(id = 7, ...), 
    uf8 = generateUF(id = 8, ...), 
    uf9 = generateUF(id = 9, ...), 
    uf10 = generateUF(id = 10, ...),
    cf1 = generateCF(id = 1, ...), 
    cf2 = generateCF(id = 2, ...), 
    cf3 = generateCF(id = 3, ...), 
    cf4 = generateCF(id = 4, ...), 
    cf5 = generateCF(id = 5, ...), 
    cf6 = generateCF(id = 6, ...), 
    cf7 = generateCF(id = 7, ...), 
    cf8 = generateCF(id = 8, ...), 
    cf9 = generateCF(id = 9, ...), 
    cf10 = generateCF(id = 10, ...),
    wfg1 = generateWFG(id = 1, ...),
    wfg2 = generateWFG(id = 2, ...),
    wfg3 = generateWFG(id = 3, ...),
    wfg4 = generateWFG(id = 4, ...),
    wfg5 = generateWFG(id = 5, ...),
    wfg6 = generateWFG(id = 6, ...),
    wfg7 = generateWFG(id = 7, ...),
    wfg8 = generateWFG(id = 8, ...),
    wfg9 = generateWFG(id = 9, ...),
    mop1 = generateMOP(id = 1, ...),
    mop2 = generateMOP(id = 2, ...),
    mop3 = generateMOP(id = 3, ...),
    mop4 = generateMOP(id = 4, ...),
    mop5 = generateMOP(id = 5, ...),
    mop6 = generateMOP(id = 6, ...),
    mop7 = generateMOP(id = 7, ...),
    mop_c1 = generateMOP_C(id = 1, ...),
    mop_c2 = generateMOP_C(id = 2, ...),
    mop_c3 = generateMOP_C(id = 3, ...),
    bk1 = generateBK1(...),
    dgo1 = generateDGO1(...),
    dgo2 = generateDGO2(...),
    fa1 = generateFA1(...),
    far1 = generateFar1(...),
    fes1 = generateFES1(...),
    fes2 = generateFES2(...),
    fes3 = generateFES3(...),
    ff1 = generateFF1(...),
    ikk1 = generateIKK1(...),
    im1 = generateIM1(...),
    jos1 = generateJOS1(...),
    jos2 = generateJOS2(...),
    kur1 = generateKur1(...),
    lrs1 = generateLRS1(...),
    ltdz1 = generateLTDZ1(...),
    le1 = generateLE1(...),
    mhhm1 = generateMHHM1(...),
    mhhm2 = generateMHHM2(...),
    mlf1 = generateMLF1(...),
    mlf2 = generateMLF2(...),
    qv1 = generateQV1(...),
    sch1 = generateSch1(...),
    sp1 = generateSP1(...),
    ssfyy1 = generateSSFYY1(...),
    ssfyy2 = generateSSFYY2(...),
    sk1 = generateSK1(...),
    sk2 = generateSK2(...),
    tkly1 = generateTKLY1(...),
    vu1 = generateVU1(...),
    vu2 = generateVU2(...),
    vfm1 = generateVFM1(...),
    zlt1 = generateZLT1(...),
    stop("Unknown ID")
  )
}